[platformio]
default_envs = esp32-s3-8048s043c-rtype

[env]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.37
framework = espidf
build_flags =
    -Iinclude
    -DRTYPE_DISPLAY_ONLY=1
    -DBOARD_HAS_PSRAM
    -Wno-error=implicit-function-declaration

[env:esp32-s3-8048s043c-rtype]
board = 4d_systems_esp32s3_gen4_r8n16
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.esp32s3
    -DRTYPE_TARGET_S3=ON
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
upload_speed = 460800
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -DRTYPE_BOARD_ESP32_8048S043C=1
    -DCYD_BOARD_ESP32_8048S043C=1
lib_ignore =
    m5stack_tab5
    espressif__esp_lcd_ili9881c
    espressif__esp_lcd_st7703
    espressif__esp_lcd_touch_gt911
    espressif__esp_lcd_touch_st7123
    espressif__esp_codec_dev
    espressif__usb_host_hid

[env:esp32-p4-tab5-rtype]
board = m5stack-tab5-p4
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.esp32p4
    -DRTYPE_TARGET_TAB5=ON
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_80:F1:B2:D1:46:0D-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_80:F1:B2:D1:46:0D-if00
upload_speed = 921600
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -DRTYPE_BOARD_M5STACK_TAB5_ESP32P4=1
lib_ignore =
    lcd_cyd
